services:
    homemonitoring:
        image: ghcr.io/tdurouchoux/home_monitoring:latest
        container_name: homemonitoring
        restart: unless-stopped
        volumes:
            - ./config:/app/config
            - ./log:/app/log
        devices:
            - /dev/i2c-1
            - /dev/ttyS0
        network_mode: host
        # command: "/app/config/monitoring_config.yaml --debug"
