mqtt:
    broker: localhost
    port: 1883
    username: ${oc.env:MQTT_USERNAME}
    password: ${oc.env:MQTT_PASSWORD}
    base_topic: "homeassistant"

sensors:
    - type: system_usage
      name: RPI
      location: living_room
      nb_retry_measure: 3
      qos: 1
      period: 1
      buffer_time: 10
      buffer_op: max

    - type: bme280
      name: Bedroom sensor
      location: bedroom
      nb_retry_measure: 3
      qos: 1
      period: 5

    - type: bme680
      name: Kitchen sensor
      location: kitchen
      nb_retry_measure: 3
      qos: 1
      period: 5

    - type: teleinfo
      name: Linky
      location: garage
      nb_retry_measure: 3
      qos: 1
      parameters:
          serial_port: "/dev/ttyAMA0"
