version: 1
disable_existing_loggers: False
formatters:
    file_formatter:
        format: "%(asctime)s %(name)s [%(levelname)s] - %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
    console_handler:
        class: rich.logging.RichHandler
        level: INFO
        rich_tracebacks: True
    file_handler:
        class: logging.FileHandler
        level: INFO
        formatter: file_formatter
        filename: log/home_monitoring.log
        mode: a
root:
    level: INFO
    handlers: [console_handler, file_handler]
